name: Seed Sanity production dataset

on:
  workflow_dispatch: {}
  push:
    branches: [ main ]

jobs:
  seed:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install --no-audit --no-fund

      - name: Debug: show presence of secrets
        run: |
          echo "SANITY_PROJECT_ID set: ${SANITY_PROJECT_ID:+yes}"
          echo "SANITY_DATASET set: ${SANITY_DATASET:+yes}"
          echo "SANITY_TOKEN set: ${SANITY_TOKEN:+yes}"

      - name: Run seeding script
        env:
          SANITY_PROJECT_ID: ${{ secrets.SANITY_PROJECT_ID }}
          SANITY_DATASET: ${{ secrets.SANITY_DATASET }}
          SANITY_TOKEN: ${{ secrets.SANITY_TOKEN }}
        run: node studio/scripts/seedCookies.js
